const DyFormColumnTypeEnum ={
  COMMON: 'COMMON',
  INPUT:"INPUT",
  INPUT_AREA:"INPUT_AREA",
  DATE: "DATE",
  MONTH: "MONTH",
  DATE_RANGE: "DATE_RANGE",
  DATETIME: "DATETIME",
  IMAGE: "IMAGE",
  FILE:'FILE',
  LABEL:'LABEL',
  TREE_SELECT:'TREE_SELECT',
  COMMON_SELECT:"COMMON_SELECT",
  COMMON_MULTIPLE_SELECT: "COMMON_MULTIPLE_SELECT"
}
export default DyFormColumnTypeEnum
