#根据模板生成pdf配置，需要安装wkhtmltopdf
#pdf:
#  html-to-pdf:
#    html-temp-path: /home/base-project/generate/html/
#    wk-html-to-pdf-bin-path: wkhtmltopdf
#    pdf-path: /home/base-project/generate/pdf/
#流程引擎初始化
flowable:
  #关闭定时任务job
  async-executor-activate: false
  #关闭无用功能
  idm:
    enabled: false
  cmmn:
    enabled: false
  dmn:
    enabled: false
  app:
    enabled: false
  form:
    enabled: false
  event registry:
    enabled: false
ip:
  #数据库 IP
  database: 192.168.1.18
  #redis IP
  #  redis: 192.168.1.17
  #系统 IP
  app: 192.168.1.18
  # xxl-job定时任务 IP
  #  xxl-job: 192.168.1.18
  # mq 地址IP
#  rabbitmq: 192.168.1.18

#DINGDING相关配置
#baseUrl:
#  fgUrl: http://${ip.app}:8850
#  bgUrl: http://${ip.app}:${server.port}
#  # 结果回调需要域名配置
#  callBackUrl: https://xxxxxx/demo
#dingding:
#  dingdingPropertyMap:
#    rd:
#      robotCode: xxxxxxxxxxxxxxxxxx
#      appKey: xxxxxxxxxxxxxxxxxx
#      appSecret: xxxxxxxxxxxxxxxxxx
#      agentId: xxxxxxxxxxxxxxxxxx
#      corpId: xxxxxxxxxxxxxxxxxx
#      authUrl: ${baseUrl.fgUrl}/#/auth/authLogin?loginType=dingdingLogin
#      resultUrl: ${baseUrl.fgUrl}/#/result/index

#邮件相关配置
#msg:
#  email:
#    enable: true
#    host: smtp.exmail.qq.com
#    port: 465
#    username: xxxxxxxxxxxx
#    password: xxxxxxxxxxxx
#    sender: 邮件发送人
#    ssl: true
spring:
  #  rabbitmq:
  #    host: ${ip.rabbitmq}
  #    port: 5672
  #    username: xxxxxxxxxxxx
  #    password: xxxxxxxxxxxx
  # 多数据源配置
  datasource:
    primary: demo #设置默认的数据源或者数据源组,默认值即为master
    dataSourcePropertyMap:
      demo:
        url: jdbc:mysql://${ip.database}:3306/demo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: demo_user
        password: cF6{bG2@mZ
  #      demo1:
  #        url: jdbc:mysql://${ip.database}:3306/demo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
  #        driver-class-name: com.mysql.cj.jdbc.Driver
  #        username: xxxxxxxxxxxx
  #        password: xxxxxxxxxxxx
  session:
    # 推荐使用REDIS，如下以内存为例搭配caffeine
    # 选择REDIS的话需要在业务模块引入redis模块，同时需要配置redisson
    # 选择NONE的话需要在业务模块引入caffeine模块，session在应用重启后会消失，不推荐使用，仅测试使用
    store-type: NONE
    timeout: 2H
    redis:
      namespace: spring:session
#  redis:
#    host: ${ip.redis}
#    port: 6379
#    password: 123456
#    database: 5
#    lettuce:
#      pool:
#        max-active: 200 #池中可以分配的最大连接数，使用负值表示无限制。
#        max-idle: 100 #池中'空闲'连接的最大数量，使用负值表示空闲连接的数量不限。
#        min-idle: 20 #池中要维护的最小空闲连接数的目标，此设置仅在为正时有效。
#        max-wait: -1ms #池中连接耗尽时引发异常之前，等待连接分配的最长时间。使用负值可以无限期等待。
#  redisson:
#    host: ${ip.redis}
#    port: 6379
#    database: 6
#    password: 123456
logging:
  # 选择对应日志配置
  config: classpath:logging-prod.xml
file:
  # 文件存储类型，可选值：local、minio，推荐使用minio
  # 选择minio时，需要配置minio信息，其中file.path为桶名称
  # 选择local时，需要配置file.path路径，例如（window下F:\home）或 （linux下/home/file）
  type: local
  path: F:\home
  # 是否需要申请授权才能看到文件，如果开启，则需要自行实现三个类
  # FileReadInterceptor 核心拦截类
  # FileApplyInterceptor 申请审批拦截类（如提醒审批人）
  # FileAuthInterceptor 授权结果拦截类（如提醒申请人）
  auth: false
#minio:
#  endpoint: http://192.168.1.14:8092
#  accesskey: xxxxxxxxxxxx
#  secretkwy: xxxxxxxxxxxx

### 文档以及调度中心下载地址： https://www.xuxueli.com/xxl-job/
#xxl:
#  job:
#    enable: true
#    ### 调度中心部署根地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
#    adminAddress: http://${ip.xxl-job}:8177/xxl-job-admin
#    ### 执行器通讯TOKEN [选填]：非空时启用；
#    accessToken: default_token
#    ### 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
#    executorAppname: system
#    ### 执行器注册 [选填]：优先使用该配置作为注册地址，为空时使用内嵌服务 ”IP:PORT“ 作为注册地址。从而更灵活的支持容器类型执行器动态IP和动态映射端口问题。
#    executorAddress:
#    ### 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
#    executorIp:
#    ### 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
#    executorPort: 9997
#    ### 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
#    executorLogPath: ./logs/jobhandler
#    ### 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
#    executorLogretentiondays: 30

